### PR TITLE
Update code to match changes in the Java version.

### PR DESCRIPTION
**Pull request by huan086**
Java version is updated to handle large dictionary of search terms. It also added FindFirst and Matches.

I'm not sure there's need to target [.NET standard < 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#which-net-standard-version-to-target). Documentation [recommends targeting .NET Standard 2.0 and .NET 5+](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#when-to-target-net50-or-net60-vs-netstandard). Since .NET 5 is end of support, I've target .NET 6.

I have no experience in packaging for nuget. Not sure if there is a need to specifically target .NET 4.6. Please edit the framework targets before merging.

### CODE REVIEW

**Comment by VitaliyMF** [comment]
First of all, thank you for the contribution!

Could you clarify what changes are made in the algorithm itself? I see that you changed 'tabs' indents with 'spaces' (I prefer to use 'tabs', actually) so it's hard to detect what is actually changed in the diff.

**Comment by huan086** [comment]
Instead of recursion, which uses the stack, the code is changed to use a Queue, which allocates on the heap. This prevents StackOverflowException with large dictionaries.

Let me change to tabs. VS Code auto-detect as spaces somehow

**Comment by huan086** [comment]
Minimized the whitespace changes. There's stylistic changes though, like using Pascal case for method names, using lambda method bodies etc.

For algo change, I did try to make it as close to the Java version as possible, such as the use of the range [a..b] syntax instead of Substring, since Java substring takes start and end index rather than length

**Comment by VitaliyMF** [comment]
@huan086 Thanks a lot, looks good!

Only notice - could you translate Chinese comments to English?..

**Comment by huan086** [comment]
I don't understand technical terms in Chinese. Pumped it through Bing translate. Hope it tallies with what the algo is doing...

**Pull request merged**
