### PR TITLE
Restore List

### PR DESCRIPTION
**Pull request by Nuklon**
List has a lot more functions available.

### CODE REVIEW

**Comment by VitaliyMF** [comment]
This is not a backward compatible change; if you want to rely on `Parse` internals, you may explicitly cast `IList<>` to `List<>` if you need this for some reason.

**Comment by Nuklon** [comment]
It was a List before 1.1.0...

**Comment by Nuklon** [comment]
See: 
https://github.com/nreco/AhoCorasickDoubleArrayTrie/blob/efb7fa9132efa65869f44f75ace87ce8237ad53d/src/NReco.Text.AhoCorasickDoubleArrayTrie/AhoCorasickDoubleArrayTrie.cs#L81

**Comment by VitaliyMF** [comment]
@Nuklon makes sense - this change was introduced in #7 by @huan086 and I missed this incompatible change during code review. Thanks!

**Comment by Nuklon** [comment]
No problem, can you release a new version so I can update? 🙂

**Comment by VitaliyMF** [comment]
Shipped in 1.1.1

**Pull request merged**
